---
apiVersion: v1
kind: Service
metadata:
  name: mydb
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9376
  selector:
    app: vproapp
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: memcache
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9377
  selector:
    app: vproapp
  type: LoadBalancer
